### ISSUE TITLE
Responsive Issue

### ISSUE THREAD

**Issue by darshancc23** [osl-vvce/osl-vvce.github.io#4]
There's an issue with the brand-heading in responsive mode.
![capture](https://user-images.githubusercontent.com/31676962/44619026-0eb76800-a89e-11e8-8e30-ca1c6caee108.PNG)
The issue is when the brand heading is in Kannada
![capture1](https://user-images.githubusercontent.com/31676962/44619034-20990b00-a89e-11e8-9714-2588f2fb3cf1.PNG)

**Comment by shreevari** [comment]
This is observed because kannada text are wider than other languages. I feel there should be an adjustment(decreased font size) for kannada as an exception, or try out a different kannada font.

**Comment by darshancc23** [comment]
Reducing the font-size using **media queries** is probably the best option.
