### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by clintondsza** [osl-vvce/osl-vvce.github.io#45]
Font and style should be changed

**Comment by sanjithpk** [comment]
What font should we use?

**Comment by clintondsza** [comment]
> What font should we use?

Will let you know

**Comment by clintondsza** [comment]
- https://fonts.google.com/specimen/Montserrat (H)
https://fonts.google.com/specimen/Josefin+Sans
- https://fonts.google.com/specimen/Quicksand (Medium 500) (H)
https://fonts.google.com/specimen/Quicksand (Regular 400)
- https://fonts.google.com/specimen/Oswald (H)
https://fonts.google.com/specimen/EB+Garamond
- https://fonts.google.com/specimen/Roboto (H)
https://fonts.google.com/specimen/Roboto+Condensed

**Comment by sanjithpk** [comment]
articulat
