### ISSUE TITLE
New Illustrations

### ISSUE THREAD

**Issue by sanjithpk** [osl-vvce/osl-vvce.github.io#47]
PNG/SVG illustrations for the About Page

**Comment by sanjithpk** [comment]
@clintondsza  here are few websites I found, please be patient and go through these and tell me if you have any luck in finding illustrations.

https://growwwkit.com/illustrations/phonies
https://www.openpeeps.com/
https://www.oldbookillustrations.com/
https://generative-placeholders.glitch.me/
https://lukaszadam.com/illustrations
https://www.wireframer.art/
https://undraw.co/
https://illlustrations.co/
https://freellustrations.com/
https://www.glazestock.com/
https://fresh-folk.com/
https://www.opendoodles.com/
https://icons8.com/ouch
https://absurd.design/chapter1.html
https://mixkit.co/art/
https://iconscout.com/paper-illustrations
https://delesign.com/free-designs/graphics/
https://www.kapwing.com/404-illustrations
https://search.creativecommons.org/
https://absurd.design/

**Comment by clintondsza** [comment]
I went through these links. Just visit these link below, and choose kind of people you like (LOL) and let me know @sanjithpk @nimeshm05  
https://freellustrations.com/
https://undraw.co/illustrations
https://delesign.com/free-designs/graphics
> https://www.glazestock.com/browse
