### ISSUE TITLE
Properly size images

### ISSUE THREAD

**Issue by darshancc23** [osl-vvce/osl-vvce.github.io#6]
Use appropriate sizes for images rather than scaling it down, this will improve performance and make the images sharper. The OSC logo looks bad.

**Comment by sanjithpk** [comment]
I changed it a bit, check now.

**Comment by darshancc23** [comment]
Natural dimensions of the logo: 3610 × 1515 pixels. 
You are scaling this to 180 x 80 pixels. Make sure the natural dimensions of the source image is 180 x 80 pixels.

**Comment by sanjithpk** [comment]
Actually I made it to 190 x 80 pixels, that was the minor change that I did anyway.

**Comment by sanjithpk** [comment]
#11 fixed the issue
