### ISSUE TITLE
excess slick-dots

### ISSUE THREAD

**Issue by srinivasharsha** [osl-vvce/osl-vvce.github.io#8]
![image](https://user-images.githubusercontent.com/33371113/44621293-4388e680-a8c1-11e8-97e9-621f3a1dcb9e.png)

More than required slick-dots are present.

**Comment by sanjithpk** [comment]
If I remove excess, for mobile view it'll be a problem. Darshan, if you know how to tell me.

**Comment by shreevari** [comment]
There are three quotes and three slick dots.
Where is it extra?
![screenshot_2018-08-26 osl vvce](https://user-images.githubusercontent.com/15689915/44625306-b0cd6380-a923-11e8-831b-e697a1be0fd9.png)
![screenshot_2018-08-26 osl vvce 1](https://user-images.githubusercontent.com/15689915/44625307-b165fa00-a923-11e8-9944-e33e18a8f72d.png)
![screenshot_2018-08-26 osl vvce 2](https://user-images.githubusercontent.com/15689915/44625308-b165fa00-a923-11e8-98bc-aaadfef8b88f.png)
